import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import Provider from "./Provider";

const notoSansKr = Noto_Sans_KR({ 
  subsets: ["latin"],
  weight:["100","400","700","900"] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
